# path to the excel files with data
filename_rozliczenie_miesieczne = "rozliczenie_miesieczne_*.xlsx"
filename_korekty = "D:/python_data/projekt/kpi/kpi_data/korekty.xlsx"
filename_folder = "D:/python_data/projekt/kpi/kpi_data/"
filename_processed_data = "D:/python_data/projekt/kpi/kpi_data/processed_data.csv"
filename_checked_week = "D:/python_data/projekt/kpi/kpi_data/checked_week.csv"
filename_checked_month = "D:/python_data/projekt/kpi/kpi_data/checked_month.csv"
filename_checked_date = "D:/python_data/projekt/kpi/kpi_data/checked_date.csv"
filename_chart_week = "D:/python_data/projekt/kpi/kpi_data/chart_week.html"
filename_chart_date = "D:/python_data/projekt/kpi/kpi_data/chart_date.html"